### ISSUE TITLE
VET error

### ISSUE THREAD

**Issue by AmberStuver** [gwpy/vet#16]
VET no longer runs (including analyses that ran fine before).  I am seeing this error:

```
 .  /home/duncan.macleod/opt/gwpysoft-2.7/bin/activate
(gwpysoft-2.7) [ray.dean@ldas-pcdev2 BlipL]$ gw_summary gps 1168452598 1168798198 -f defaults.ini -f Blipl.ini --verbose
/home/duncan.macleod/opt/gwpysoft-2.7/bin/gw_summary:58: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'TkAgg' by the following code:
  File "/home/duncan.macleod/opt/gwpysoft-2.7/bin/gw_summary", line 36, in <module>
    from gwpy import time
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/__init__.py", line 35, in <module>
    from . import (
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/plot/__init__.py", line 35, in <module>
    from .plot import Plot

  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/plot/plot.py", line 30, in <module>
    from matplotlib import (backends, figure, get_backend, _pylab_helpers)
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 16, in <module>
    line for line in traceback.format_stack()

  use('Agg')
Traceback (most recent call last):
  File "/home/duncan.macleod/opt/gwpysoft-2.7/bin/gw_summary", line 78, in <module>
    from gwsumm.tabs import (TabList, get_tab)
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwsumm/tabs/__init__.py", line 25, in <module>
    from .builtin import *
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwsumm/tabs/builtin.py", line 36, in <module>
    from ..plot import get_plot
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwsumm/plot/__init__.py", line 56, in <module>
    from .sei import *
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwsumm/plot/sei.py", line 26, in <module>
    from matplotlib.pyplot import subplots
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 4, in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/matplotlib/backends/tkagg.py", line 5, in <module>
    from six.moves import tkinter as Tk
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/six.py", line 82, in _import_module
    __import__(name)

ImportError: No module named Tkinter
```

Any assistance is welcome!

**Comment by AmberStuver** [comment]
VET is still not working, but getting farther into the analysis before giving an "read_ligolw() got an unexpected keyword argument 'get_as_columns'" error.

I've included the output below.

Thanks!
```

[ray.dean@ldas-pcdev2 BlipH]$ . /home/duncan.macleod/opt/gwpysoft-2.7/bin/activate
(gwpysoft-2.7) [ray.dean@ldas-pcdev2 BlipH]$ gw_summary gps 1164564597 1174348818 -f defaults.ini -f Blip1.ini --verbose

------------------------------------------------------------------------------
Welcome to the GW summary information system command-line interface
------------------------------------------------------------------------------

This is process 1382145
You have selected gps mode.
Start time 2016-11-30 18:09:40.000 (1164564597.0)
End time: 2017-03-24 00:00:00.000 (1174348818.0)
Output directory: /home/ray.dean/public_html/Hanford/BlipH/1164564597-1174348818

Loading configuration...
    Loaded 1 plugins:
        <module 'gwvet.tabs' from '/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwvet/tabs.pyc'>
    Loaded 0 units
    Loaded 0 channels
    Loaded 2 states
    Loaded 0 rcParams
    Loaded 1 tabs [1 parents overall]
-------------------------------------------------
Processing Blip1
    Downloaded 326 segments for H1:DMT-ANALYSIS_READY:1 (99.55% coverage).
States finalised [1 total]
    Science: 326 segments | 6124462.0 seconds [DEFAULT]
Processing 'Science' state:
    Read 2802 segments for H1:BLIP_TEST:1 (68.10% coverage).
    Grabbing Omicron triggers for H1:GDS-CALIB_STRAINTraceback (most recent call last):
  File "/home/duncan.macleod/opt/gwpysoft-2.7/bin/gw_summary", line 682, in <module>
    datafind_error=opts.on_datafind_error, **cache)
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwsumm/tabs/data.py", line 366, in process
    **stateargs)
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwvet/tabs.py", line 310, in process_state
    format=self.etgformat)
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwsumm/triggers.py", line 238, in get_triggers
    nproc=nproc, **read_kw)
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwsumm/triggers.py", line 427, in read_cache
    table = EventTable.read(cache, **kwargs)
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/table/table.py", line 207, in read
    tab = io_read_multi(vstack, cls, source, *args, **kwargs)
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/io/mp.py", line 97, in read_multi
    nproc, _read_single_file, files, verbose=verbose, unit='files')
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/utils/mp.py", line 123, in multiprocess_with_queues
    return list(map(_inner, inputs))
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/utils/mp.py", line 110, in _inner
    return func(x)
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/io/mp.py", line 82, in _read_single_file
    return fobj, io_read(cls, fobj, *args, **kwargs)
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/astropy/io/registry.py", line 531, in read
    data = reader(*args, **kwargs)
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/table/io/utils.py", line 43, in decorated_func
    tab = func(*args, **kwargs)
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/table/io/ligolw.py", line 346, in read_table
    return Table(read_ligolw_table(source, tablename=tablename, **read_kw),
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/io/ligolw.py", line 274, in read_table
    **kwargs)
TypeError: read_ligolw() got an unexpected keyword argument 'get_as_columns'
```

**Comment by AmberStuver** [comment]
I am now getting a new error (the below was run at LHO):

```
[stuver@ldas-pcdev2 Ray]$ ./run.sh

------------------------------------------------------------------------------
Welcome to the GW summary information system command-line interface
------------------------------------------------------------------------------

This is process 520703
You have selected gps mode.
Start time 2017-08-11 00:00:00.000 (1186444818.0)
End time: 2017-08-21 00:00:00.000 (1187308818.0)
Output directory: /home/stuver/public_html/VET/Ray/1186444818-1187308818

Loading configuration...
    Loaded 1 plugins:
        <module 'gwvet.tabs' from '/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwvet/tabs.pyc'>
    Loaded 0 units
    Loaded 0 channels
    Loaded 2 states
    Loaded 0 rcParams
    Loaded 1 tabs [1 parents overall]

-------------------------------------------------
Processing TEST
    Downloaded 20 segments for H1:DMT-ANALYSIS_READY:1 (100.00% coverage).
States finalised [1 total]
    Science: 20 segments | 706172.0 seconds [DEFAULT]
Processing 'Science' state:
    Read 0 segments for H1:HVETO_C00:1 (0.00% coverage).
    Grabbing Omicron triggers for H1:GDS-CALIB_STRAINTraceback (most recent call last):
  File "/home/duncan.macleod/opt/gwpysoft-2.7/bin/gw_summary", line 682, in <module>
    datafind_error=opts.on_datafind_error, **cache)
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwsumm/tabs/data.py", line 366, in process
    **stateargs)
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwvet/tabs.py", line 310, in process_state
    format=self.etgformat)
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwsumm/triggers.py", line 224, in get_triggers
    **trigfindkwargs)
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/trigfind/core.py", line 104, in find_trigger_files
    return finder(channel, start, end, **kwargs)
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/trigfind/core.py", line 166, in find_detchar_files
    start, end, ngps=5)
  File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/trigfind/core.py", line 240, in _find_in_gps_dirs
    if ce.segment.intersects(span):
TypeError: [1186447247 ... 1186491565)

```
